### ISSUE TITLE
Redundant splitting of move string in prompt()

### ISSUE THREAD

**Issue by ngjunsiang** [recreationx/ChessGame#16]
## Issue

[chess.py line 172](https://github.com/recreationx/ChessGame/blob/master/chess.py#L172): start and end coordinates have already been split in line 170.

## Suggested resolution

Use the `start` and `end` variables to print the player's move

**Comment by recreationx** [comment]
#70

**Comment by recreationx** [comment]
Changed in
c98b27c938c269ef45fef25212c9382fbec8562a
